#!/bin/bash
echo "🔍 Verifying Railway Configuration"
echo "Domain: web-production-1d574.up.railway.app"
echo ""
echo "To check your Railway variables, please:"
echo ""
echo "1. Go to Railway Dashboard: https://railway.app"
echo "2. Find your project (likely 'distinguished-balance' or similar)"
echo "3. Click your web service"
echo "4. Go to Variables tab"
echo ""
echo "OR run this to link and check:"
echo "  railway link"
echo ""
echo "Required variables to verify:"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "✅ GOOGLE_CLIENT_ID"
echo "✅ GOOGLE_CLIENT_SECRET"
echo "✅ GOOGLE_REFRESH_TOKEN"
echo "✅ GOOGLE_REDIRECT_URI (should be: https://web-production-1d574.up.railway.app/oauth2callback)"
echo "✅ SMTP_HOST (smtp.gmail.com)"
echo "✅ SMTP_PORT (587)"
echo "✅ SMTP_USER (support@stuchai.com)"
echo "✅ SMTP_PASSWORD"
echo "✅ REPORT_EMAIL_FROM (support@stuchai.com)"
echo "✅ REPORT_EMAIL_TO"
echo "✅ DATABASE_URL (auto-created by Railway)"
echo "✅ SITE_URL (https://www.berganco.com)"
echo "✅ PORT (3000)"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"

